apiVersion: v1
kind: Service
metadata:
  name: chutvrc-eval-runner
  namespace: chutvrc
  labels:
    app: chutvrc-eval-runner
spec:
  type: ClusterIP
  selector:
    app: chutvrc-eval-runner
  ports:
    - name: ws
      port: 9099
      targetPort: 9099
      protocol: TCP
